language: php
php:
  - 5.6

services:
  - postgresql
  - mongodb
  - elasticsearch

addons:
  postgresql: "9.3"

before_install:
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install

before_script:
  - psql -c 'create database coyote_test;' -U postgres
  - mongo coyote_test --eval 'db.addUser("travis", "test");'
  - cp .env.testing .env
  - cp tests/acceptance.suite.yml.travis tests/acceptance.suite.yml
  - php artisan migrate --seed --env="testing"
  - php vendor/bin/codecept build
  - make file-permission
  - phantomjs --webdriver=4444 2>&1 >/dev/null &
  - sleep 5
  - php -S 127.0.0.1:8000 -t public/ 2>&1 >/dev/null &
  - sleep 5
  - php artisan es:create
  - php artisan es:mapping

script: php vendor/bin/codecept run