sudo: true
language: php
php:
  - 7.2

cache:
  directories:
    - node_modules
    - vendor
    - yarn

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
  - chmod +x ~/docker-compose
  - sudo mv ~/docker-compose /usr/local/bin/docker-compose
  - cp .env.testing .env

install:
  - sudo service postgresql stop
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec php composer install
  - docker-compose exec php php artisan migrate --seed
  - docker-compose exec node yarn install
  - docker-compose exec node yarn prod

before_script:
  - docker-compose exec php php vendor/bin/codecept build
  - docker-compose exec php php artisan config:clear
  - docker-compose exec php php artisan route:clear

script:
  - docker-compose exec php php vendor/bin/codecept run
  - docker-compose exec php php vendor/bin/phpunit
#  - docker-compose exec php php artisan dusk

after_script:
  - docker-compose stop
  - docker-compose rm -f
  - cat $TRAVIS_BUILD_DIR/storage/logs/*.log
  - cat $TRAVIS_BUILD_DIR/tests/_output/*.html
