language: php
php:
  - 5.5
  - 5.6

services: postgresql

addons:
  postgresql: "9.3"

install:
  - composer install

before_script:
  - psql -c 'create database coyote_test;' -U postgres
  - cp .env.testing .env
  - php artisan migrate --seed --env="testing"
  - php vendor/bin/codecept build
  - chmod -R 777 storage/
  - phantomjs --webdriver=4444 2>&1 >/dev/null &
  - sleep 5
  - php artisan serve 2>&1 >/dev/null &
  - sleep 1

script: php vendor/bin/codecept run