sudo: true

cache:
  directories:
    - node_modules
    - vendor
    - yarn

before_install:
  - cp .env.testing .env
  - chmod -R 0777 storage bootstrap/cache public
  - mkdir public/uploads
  - ls -lsa $TRAVIS_BUILD_DIR
  - id -u

install:
  - sudo service postgresql stop
  - rm -rf /var/lib/postgresql/data
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec php make install

before_script:
  - docker-compose exec php php vendor/bin/codecept build
  - docker-compose exec php php artisan config:clear
  - docker-compose exec php php artisan route:clear

script:
#  - sudo chmod 0777 storage/logs/*.log
#  - docker-compose exec php php vendor/bin/codecept run
#  - docker-compose exec php php vendor/bin/phpunit
  - docker-compose exec php php artisan dusk

after_script:
  - docker-compose stop
  - docker-compose rm -f
  - cat $TRAVIS_BUILD_DIR/storage/logs/*.log
  - cat $TRAVIS_BUILD_DIR/tests/_output/*.html
  - cat $TRAVIS_BUILD_DIR/tests/Browser/console/*.*
