language: php
php:
  - 5.5
  - 5.6

services: postgresql

install:
  - composer install

before_script:
  - psql -c 'create database coyote_test;' -U postgres
  - cp .env.testing .env
  - php artisan migrate --seed --env="testing"

script: php vendor/bin/codecept run