sudo: true

cache:
  directories:
    - node_modules
    - vendor
    - yarn

before_install:
  - sudo addgroup --gid 1000 nginx
  - sudo useradd --uid 1000 -g nginx nginx
  - cp .env.testing .env

install:
  - sudo service postgresql stop
  - rm -rf /var/lib/postgresql/data
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec php make install
  - mkdir public/uploads
  - sudo chown -R nginx:nginx $TRAVIS_BUILD_DIR
  - ls -lsa $TRAVIS_BUILD_DIR

before_script:
  - docker-compose exec php php vendor/bin/codecept build
  - docker-compose exec php php artisan config:clear
  - docker-compose exec php php artisan route:clear

script:
#  - sudo chmod 0777 storage/logs/*.log
  - docker-compose exec php php vendor/bin/codecept run
  - docker-compose exec php php vendor/bin/phpunit
  - docker-compose exec php php artisan dusk

after_script:
  - docker-compose stop
  - docker-compose rm -f
  - cat $TRAVIS_BUILD_DIR/storage/logs/*.log
  - cat $TRAVIS_BUILD_DIR/tests/_output/*.html
  - cat $TRAVIS_BUILD_DIR/tests/Browser/console/*.*
