language: php
php:
  - 7.0

services:
  - postgresql
  - mongodb
  - elasticsearch
  - redis-server

addons:
  postgresql: "9.3"

before_install:
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install
  - npm -g install npm@next

before_script:
  - make install-gulp
  - psql -c 'create database coyote_test;' -U postgres
  - mongo coyote_test --eval 'db.addUser("travis", "test");'
  - cp .env.testing .env
  - cp tests/acceptance.suite.yml.travis tests/acceptance.suite.yml
  - php artisan migrate --seed --env="testing"
  - php vendor/bin/codecept build
  - make file-permission
  - make install-assets
  - make assets-production
  - phantomjs --webdriver=4444 2>&1 >/dev/null &
  - sleep 5
  - php -S 127.0.0.1:8000 -t public/ 2>&1 >/dev/null &
  - sleep 5
  - php artisan es:create --force
  - php artisan es:mapping --force

script: php vendor/bin/codecept run

after_script:
  - cat $TRAVIS_BUILD_DIR/storage/logs/*.log