version: '3.5'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - ./docker/postgres/postgresql.auto.conf:/var/lib/postgresql/data/postgresql.auto.conf

  nginx:
    ports:
      - 80:80


