version: '3.1'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  php:
    image: 4programmers/php-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/coyote.ini:/usr/local/etc/php/conf.d/coyote.ini
    environment:
      DB_PORT: 5432
      DB_HOST: db
      REDIS_HOST: ${REDIS_HOST}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - php

  redis:
    image: redis:latest

  elasticsearch:
    image: elasticsearch:5.6.14
    ports:
      - 9200:9200
#    mem_limit: 1g
    volumes:
        - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  minio:
    image: minio/minio
    volumes:
      - minio:/data
#    ports:
#      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 minio minio123 --api s3v4;
      /usr/bin/mc mb minio/coyote;
      /usr/bin/mc policy set download minio/coyote;
      exit 0;
      "

volumes:
  postgres:
  elasticsearch:
  minio:
