version: '2'

services:
    db:
        image: postgres
        restart: always
        volumes:
            - ./.data/pgsql:/var/lib/postgresql/data:z
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            PGDATA: /tmp
        ports:
            - 33061:3306

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    php:
        build:
          context: ./
          dockerfile: ./docker/php/Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/coyote.ini:/usr/local/etc/php/conf.d/coyote.ini
        environment:
            DB_PORT: 5432
            DB_HOST: db
            REDIS_HOST: ${REDIS_HOST}
            ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}

    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/coyote.conf
            - ./.data/logs/nginx:/var/log/nginx:z
        working_dir: /var/www
        volumes_from:
            - php
        depends_on:
            - php
        ports:
            - 8880:80

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/.data/mongodb
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_HOST=${MONGO_HOST}
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
          - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
        volumes:
          - ./.data/mongodb:/.data/mongodb
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null

    redis:
        image: redis:latest
        ports:
            - 6379:6379

    elasticsearch:
        image: elasticsearch:5.6.14
        ports:
            - 9200:9200
        mem_limit: 1g
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    smtp:
        image: namshi/smtp
        environment:
          - PORT=${MAIL_PORT}
