version: '3.5'

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/postgresql.auto.conf:/var/lib/postgresql/data/postgresql.auto.conf
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: coyote
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: coyote
    networks:
      - coyote
    secrets:
      - POSTGRES_PASSWORD

  php:
    image: 4programmers/coyote:latest
    build:
      context: .
      dockerfile: docker/coyote/Dockerfile
      cache_from:
        - 4programmers/coyote:latest
    volumes:
      - codebase:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: /run/secrets/APP_KEY
#      APP_KEY: "base64:mxXTLiTXOcsKZ+u6OoYVaZFNYAwM91nmbzrdEV+mUfE="
      APP_URL: https://4programmers.net
      API_HOST: api.4programmers.net

      SESSION_DOMAIN: ".4programmers.net"

      DB_PORT: 5432
      DB_HOST: db
      DB_DATABASE: coyote
      DB_USERNAME: coyote
      DB_PASSWORD: /run/secrets/POSTGRES_PASSWORD

      ELASTICSEARCH_HOST: elasticsearch
      REDIS_HOST: redis
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis

      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: /run/secrets/AWS_SECRET_ACCESS_KEY
      AWS_URL: /run/secrets/AWS_URL
      MINIO_ENDPOINT: http://minio:9000/

      WS_HOST: app
      WS_PORT: 8880
      WS_PROXY: /run/secrets/WS_PROXY

      MAIL_DRIVER: mailgun
      MAILGUN_DOMAIN: mg.4programmers.net
      MAILGUN_SECRET: /run/secrets/MAILGUN_SECRET

      SENTRY_DSN: /run/secrets/SENTRY_DSN

      RECAPTCHA_KEY: /run/secrets/RECAPTCHA_KEY
      RECAPTCHA_SECRET: /run/secrets/RECAPTCHA_SECRET

      P24_CLIENT_ID: /run/secrets/P24_CLIENT_ID
      P24_SALT: /run/secrets/P24_SALT
      P24_PAYMENT_URL: "https://secure.przelewy24.pl/trnDirect"
      P24_VERIFY_URL: "https://secure.przelewy24.pl/trnVerify"

      PAYLANE_USERNAME: /run/secrets/PAYLANE_USERNAME
      PAYLANE_PASSWORD: /run/secrets/PAYLANE_PASSWORD
      PAYLANE_SALT: /run/secrets/PAYLANE_SALT

      GITHUB_CLIENT_ID: /run/secrets/GITHUB_CLIENT_ID
      GITHUB_SECRET_ID: /run/secrets/GITHUB_SECRET_ID
      GITHUB_REDIRECT: "https://4programmers.net/OAuth/Github/Callback"

      GOOGLE_CLIENT_ID: /run/secrets/GOOGLE_CLIENT_ID
      GOOGLE_SECRET_ID: /run/secrets/GOOGLE_SECRET_ID
      GOOGLE_REDIRECT: "https://4programmers.net/OAuth/Google/Callback"

      FACEBOOK_CLIENT_ID: /run/secrets/FACEBOOK_CLIENT_ID
      FACEBOOK_SECRET_ID: /run/secrets/FACEBOOK_SECRET_ID
      FACEBOOK_REDIRECT: "https://4programmers.net/OAuth/Facebook/Callback"

      VENDOR_NAME: "4programmers.net Ltd"
      VENDOR_ADDRESS: "International House 776-778 Barking Road"
      VENDOR_POSTAL_CODE: "E13 9PJ"
      VENDOR_CITY: "London"
      VENDOR_COUNTRY: "United Kingdom"
    secrets:
      - APP_KEY
      - POSTGRES_PASSWORD
      - AWS_SECRET_ACCESS_KEY
      - AWS_URL
      - WS_PROXY
      - MAILGUN_SECRET
      - SENTRY_DSN
      - RECAPTCHA_KEY
      - RECAPTCHA_SECRET
      - P24_CLIENT_ID
      - P24_SALT
      - PAYLANE_USERNAME
      - PAYLANE_PASSWORD
      - PAYLANE_SALT
      - GITHUB_CLIENT_ID
      - GITHUB_SECRET_ID
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET_ID
      - FACEBOOK_CLIENT_ID
      - FACEBOOK_SECRET_ID
    networks:
      - coyote

  worker:
    image: 4programmers/coyote:latest
    networks:
      - coyote
    volumes:
      - ./:/var/www
    command: php artisan queue:listen --delay=5 -n redis

  nginx:
    image: nginx:latest
    volumes:
      - codebase:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - coyote

  redis:
    image: redis:latest
    networks:
      - coyote

  elasticsearch:
    image: elasticsearch:5.6.14
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - coyote

  minio:
    image: minio/minio
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY_FILE: /run/secrets/AWS_SECRET_ACCESS_KEY
    command: server /data
    secrets:
      - AWS_SECRET_ACCESS_KEY
    networks:
      - coyote

  mongo:
    image: mongo:3
    volumes:
      - mongo:/data/db
    networks:
      - coyote

  graylog:
    image: graylog/graylog:3.1
    volumes:
      - graylog:/usr/share/graylog/data/journal
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://beta.4programmers.info:29000/
    networks:
      - coyote
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 29000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp

  fluentbit:
    image: fluent/fluent-bit:1.3-debug
    volumes:
      - ./docker/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/lib/docker/containers:/var/log/containers
    networks:
      - coyote

  websocket:
    image: 4programmers/websocket:latest
    networks:
      - coyote
    tty: true
    environment:
      PORT: "8888"
      REDIS_HOST: "redis"
      APP_KEY: "base64:mxXTLiTXOcsKZ+u6OoYVaZFNYAwM91nmbzrdEV+mUfE="
    secrets:
      - APP_KEY
    ports:
      - 8888:8888

volumes:
  postgres:
  elasticsearch:
  minio:
  codebase:
  mongo:
  graylog:

networks:
  coyote:
    name: coyote

secrets:
  APP_KEY:
    external: true
  POSTGRES_PASSWORD:
    external: true
  AWS_SECRET_ACCESS_KEY:
    external: true
  AWS_URL:
    external: true
  WS_PROXY:
    external: true
  MAILGUN_SECRET:
    external: true
  SENTRY_DSN:
    external: true
  RECAPTCHA_KEY:
    external: true
  RECAPTCHA_SECRET:
    external: true
  P24_CLIENT_ID:
    external: true
  P24_SALT:
    external: true
  PAYLANE_USERNAME:
    external: true
  PAYLANE_PASSWORD:
    external: true
  PAYLANE_SALT:
    external: true
  GITHUB_CLIENT_ID:
    external: true
  GITHUB_SECRET_ID:
    external: true
  GOOGLE_CLIENT_ID:
    external: true
  GOOGLE_SECRET_ID:
    external: true
  FACEBOOK_CLIENT_ID:
    external: true
  FACEBOOK_SECRET_ID:
    external: true
