version: '3.5'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - ./docker/postgres/postgresql.auto.conf:/var/lib/postgresql/data/postgresql.auto.conf
      - postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: coyote
    networks:
      - coyote

  php:
    image: 4programmers/coyote:latest
    build:
      context: .
      dockerfile: docker/coyote/Dockerfile
      cache_from:
        - 4programmers/coyote:latest
    volumes:
      - codebase:/var/www
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_DATABASE: coyote
      DB_USERNAME: coyote
      DB_PASSWORD:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "base64:mxXTLiTXOcsKZ+u6OoYVaZFNYAwM91nmbzrdEV+mUfE="
      ELASTICSEARCH_HOST: elasticsearch
      REDIS_HOST: redis
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      QUEUE_DRIVER: redis

    networks:
      - coyote

  nginx:
    image: nginx:latest
    volumes:
      - codebase:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - coyote

  redis:
    image: redis:latest
    networks:
      - coyote

  elasticsearch:
    image: elasticsearch:5.6.14
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - coyote

  minio:
    image: minio/minio
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    networks:
      - coyote

  mongo:
    image: mongo:3
    volumes:
      - mongo:/data/db
    networks:
      - coyote

  graylog:
    image: graylog/graylog:3.1
    volumes:
      - graylog:/usr/share/graylog/data/journal
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://beta.4programmers.info:29000/
    networks:
      - coyote
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 29000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp

  fluentbit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./docker/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/lib/docker/containers:/var/lib/docker/containers

  websocket:
    image: 4programmers/websocket:latest
    networks:
      - coyote
    tty: true
    environment:
      PORT: "8888"
      REDIS_HOST: "redis"
      APP_KEY: "base64:mxXTLiTXOcsKZ+u6OoYVaZFNYAwM91nmbzrdEV+mUfE="
    ports:
      - 8888:8888

volumes:
  postgres:
  elasticsearch:
  minio:
  codebase:
  mongo:
  graylog:

networks:
  coyote:
    name: coyote
